version: '3'
services:
  ai_one_off:
    image: ai_one_off:latest  # Это то же самое, что и просто ai_nostra
    container_name: ai_one_off
    volumes:
      - /root/ai_one_off:/app  # Монтируем локальную директорию в контейнер


