version: '3'
services:
  ai_service:
    image: ai_one_off
    build:
      context: .
  cron:
    image: alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cronjob:/etc/cron.d
    command: crond -f -d 0



